package com.bselzer.gw2.v2.model.enumeration.extension

import com.bselzer.ktx.serialization.json.JsonContext

// Wrappers are used instead of the enums directly since while enums can help for pinpointing a specific type...
// There may be a missing or inconsistent enum sent by the API which will be no problem for deserialization because it will exist in its original form in the wrapper.

fun com.bselzer.gw2.v2.model.enumeration.wrapper.AchievementFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.AchievementFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.AchievementType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.AchievementType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.AccountAccess.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.AccountAccess>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ArmorDetailType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ArmorDetailType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ArmorWeight.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ArmorWeight>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.AttributeName.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.AttributeName>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.AttunementName.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.AttunementName>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.Binding.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.Binding>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.CategoryAchievementFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.CategoryAchievementFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.CharacterFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.CharacterFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ColorCategory.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ColorCategory>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ComboFieldType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ComboFieldType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ComboFinisherType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ComboFinisherType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.CraftingDiscipline.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.CraftingDiscipline>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ConsumableDetailType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ConsumableDetailType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ConsumableUnlockType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ConsumableUnlockType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ContainerDetailType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ContainerDetailType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.DungeonPathType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.DungeonPathType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.EffectName.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.EffectName>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.EquipmentLocation.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.EquipmentLocation>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.EquipmentSlot.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.EquipmentSlot>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.GatheringToolDetailType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.GatheringToolDetailType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.Gender.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.Gender>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.GizmoDetailType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.GizmoDetailType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.GuildEmblemFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.GuildEmblemFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.InfluenceActivity.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.InfluenceActivity>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.InfusionUpgradeFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.InfusionUpgradeFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ItemFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ItemFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ItemGameType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ItemGameType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ItemRarity.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ItemRarity>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ItemRestriction.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ItemRestriction>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.MapType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.MapType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.MaterialType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.MaterialType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.MountName.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.MountName>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.NoveltySlot.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.NoveltySlot>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.PointOfInterestType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.PointOfInterestType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.Product.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.Product>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.ProfessionFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.ProfessionFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.PvpDivisionFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.PvpDivisionFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.PvpHeroName.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.PvpHeroName>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.PvpHeroType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.PvpHeroType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.PvpLadderType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.PvpLadderType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.PvpRatingType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.PvpRatingType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.PvpResult.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.PvpResult>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.PvpTeam.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.PvpTeam>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.RaceGender.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.RaceGender>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.RaidEventType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.RaidEventType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.RecipeFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.RecipeFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.RecipeType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.RecipeType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.RegionType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.RegionType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.SabUnlockName.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.SabUnlockName>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.SalvageKitDetailType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.SalvageKitDetailType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.SkillCategory.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.SkillCategory>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.SkillFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.SkillFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.SkillSlot.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.SkillSlot>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.SkillType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.SkillType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.SkinFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.SkinFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.SpecializationName.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.SpecializationName>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.StashOperation.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.StashOperation>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.TeamMemberRole.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.TeamMemberRole>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.TrainingCategory.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.TrainingCategory>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.TrainingTrackType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.TrainingTrackType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.TraitSlot.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.TraitSlot>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.TraitTier.decodeOrNull() = value.toString().decodeOrNull<com.bselzer.gw2.v2.model.enumeration.TraitTier>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.TrinketDetailType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.TrinketDetailType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.UpgradeAction.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.UpgradeAction>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.UpgradeComponentDetailType.decodeOrNull() =
    value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.UpgradeComponentDetailType>()

fun com.bselzer.gw2.v2.model.enumeration.wrapper.UpgradeComponentFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.UpgradeComponentFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.WeaponDamageType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.WeaponDamageType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.WeaponDetailType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.WeaponDetailType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.WeaponFlag.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.WeaponFlag>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.WeaponType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.WeaponType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.WorldName.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.WorldName>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.WorldPopulationLevel.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.WorldPopulationLevel>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.WvwMapBonusType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.WvwMapBonusType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.WvwMapType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.WvwMapType>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.WvwObjectiveOwner.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.WvwObjectiveOwner>()
fun com.bselzer.gw2.v2.model.enumeration.wrapper.WvwObjectiveType.decodeOrNull() = value.decodeOrNull<com.bselzer.gw2.v2.model.enumeration.WvwObjectiveType>()

internal inline fun <reified E : Enum<E>> String.decodeOrNull(): E? = with(JsonContext) { decodeOrNull<E>() }