package com.bselzer.gw2.v2.model.enumeration.extension

import com.bselzer.gw2.v2.model.value.*
import com.bselzer.ktx.serialization.function.enumValueOrNull

// Wrappers are used instead of the enums directly since while enums can help for pinpointing a specific type...
// There may be a missing or inconsistent enum sent by the API which will be no problem for deserialization because it will exist in its original form in the wrapper.

fun AchievementFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.AchievementFlag>()
fun AchievementType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.AchievementType>()
fun AccountAccess.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.AccountAccess>()
fun ArmorDetailType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ArmorDetailType>()
fun ArmorWeight.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ArmorWeight>()
fun AttributeName.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.AttributeName>()
fun AttunementName.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.AttunementName>()
fun Binding.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.Binding>()
fun CharacterFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.CharacterFlag>()
fun ColorCategory.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ColorCategory>()
fun ComboFieldType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ComboFieldType>()
fun ComboFinisherType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ComboFinisherType>()
fun CraftingDiscipline.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.CraftingDiscipline>()
fun ConsumableDetailType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ConsumableDetailType>()
fun ConsumableUnlockType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ConsumableUnlockType>()
fun ContainerDetailType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ContainerDetailType>()
fun DungeonPathType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.DungeonPathType>()
fun EffectName.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.EffectName>()
fun EquipmentLocation.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.EquipmentLocation>()
fun EquipmentSlot.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.EquipmentSlot>()
fun GatheringToolDetailType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.GatheringToolDetailType>()
fun Gender.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.Gender>()
fun GizmoDetailType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.GizmoDetailType>()
fun GuildEmblemFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.GuildEmblemFlag>()
fun InfluenceActivity.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.InfluenceActivity>()
fun InfusionUpgradeFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.InfusionUpgradeFlag>()
fun ItemFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ItemFlag>()
fun ItemGameType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ItemGameType>()
fun ItemRarity.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ItemRarity>()
fun ItemRestriction.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ItemRestriction>()
fun MapType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.MapType>()
fun MaterialType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.MaterialType>()
fun MountName.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.MountName>()
fun NoveltySlot.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.NoveltySlot>()
fun PointOfInterestType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.PointOfInterestType>()
fun Product.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.Product>()
fun ProfessionFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.ProfessionFlag>()
fun PvpDivisionFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.PvpDivisionFlag>()
fun PvpHeroName.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.PvpHeroName>()
fun PvpHeroType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.PvpHeroType>()
fun PvpLadderType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.PvpLadderType>()
fun PvpRatingType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.PvpRatingType>()
fun PvpResult.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.PvpResult>()
fun PvpTeam.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.PvpTeam>()
fun RaceGender.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.RaceGender>()
fun RaidEventType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.RaidEventType>()
fun RecipeFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.RecipeFlag>()
fun RecipeType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.RecipeType>()
fun RegionType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.RegionType>()
fun SabUnlockName.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.SabUnlockName>()
fun SalvageKitDetailType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.SalvageKitDetailType>()
fun SkillCategory.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.SkillCategory>()
fun SkillFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.SkillFlag>()
fun SkillSlot.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.SkillSlot>()
fun SkillType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.SkillType>()
fun SkinFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.SkinFlag>()
fun SpecializationName.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.SpecializationName>()
fun StashOperation.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.StashOperation>()
fun TeamMemberRole.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.TeamMemberRole>()
fun TrainingCategory.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.TrainingCategory>()
fun TrainingTrackType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.TrainingTrackType>()
fun TraitSlot.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.TraitSlot>()
fun TraitTier.enumValueOrNull() = value.toString().enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.TraitTier>()
fun TrinketDetailType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.TrinketDetailType>()
fun UpgradeAction.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.UpgradeAction>()
fun UpgradeComponentDetailType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.UpgradeComponentDetailType>()
fun UpgradeComponentFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.UpgradeComponentFlag>()
fun WeaponDamageType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.WeaponDamageType>()
fun WeaponDetailType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.WeaponDetailType>()
fun WeaponFlag.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.WeaponFlag>()
fun WeaponType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.WeaponType>()
fun WorldName.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.WorldName>()
fun WorldPopulationLevel.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.WorldPopulationLevel>()
fun WvwMapBonusType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.WvwMapBonusType>()
fun WvwMapType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.WvwMapType>()
fun WvwObjectiveOwner.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.WvwObjectiveOwner>()
fun WvwObjectiveType.enumValueOrNull() = value.enumValueOrNull<com.bselzer.gw2.v2.model.enumeration.WvwObjectiveType>()